Traceback (most recent call last):
  File "/home/giovanni/Projects/big-data/progetto/task_1/spark-core/spark-job.py", line 57, in <module>
    main()
    ~~~~^^
  File "/home/giovanni/Projects/big-data/progetto/task_1/spark-core/spark-job.py", line 52, in main
    .reduceByKey(reducer) \
     ~~~~~~~~~~~^^^^^^^^^
  File "/home/giovanni/Projects/big-data/.venv/lib64/python3.13/site-packages/pyspark/python/lib/pyspark.zip/pyspark/rdd.py", line 3552, in reduceByKey
    return self.combineByKey(lambda x: x, func, func, numPartitions, partitionFunc)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giovanni/Projects/big-data/.venv/lib64/python3.13/site-packages/pyspark/python/lib/pyspark.zip/pyspark/rdd.py", line 3975, in combineByKey
    numPartitions = self._defaultReducePartitions()
  File "/home/giovanni/Projects/big-data/.venv/lib64/python3.13/site-packages/pyspark/python/lib/pyspark.zip/pyspark/rdd.py", line 4867, in _defaultReducePartitions
    return self.getNumPartitions()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/giovanni/Projects/big-data/.venv/lib64/python3.13/site-packages/pyspark/python/lib/pyspark.zip/pyspark/rdd.py", line 5453, in getNumPartitions
    return self._prev_jrdd.partitions().size()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/giovanni/Projects/big-data/.venv/lib64/python3.13/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
        answer, self.gateway_client, self.target_id, self.name)
  File "/home/giovanni/Projects/big-data/.venv/lib64/python3.13/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
    return f(*a, **kw)
  File "/home/giovanni/Projects/big-data/.venv/lib64/python3.13/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
        "An error occurred while calling {0}{1}{2}.\n".
        format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o25.partitions.
: org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: hdfs://localhost:9000/user/giovanni/input/cleaned_pruned_used_cars_data.csv
	at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:304)
	at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:244)
	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:332)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:210)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:294)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:290)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.$anonfun$partitions$2(RDD.scala:294)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:290)
	at org.apache.spark.api.java.JavaRDDLike.partitions(JavaRDDLike.scala:61)
	at org.apache.spark.api.java.JavaRDDLike.partitions$(JavaRDDLike.scala:61)
	at org.apache.spark.api.java.AbstractJavaRDDLike.partitions(JavaRDDLike.scala:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Input path does not exist: hdfs://localhost:9000/user/giovanni/input/cleaned_pruned_used_cars_data.csv
	at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:278)
	... 25 more

